### ISSUE TITLE
Can't type space in input

### ISSUE THREAD

**Issue by jsjoeio** [jsjoeio/mentored.dev#118]
As a user, when I am asked for input (i.e. my name, or the answer to a question) and I type a space, it doesn't work. 

*Note to self: this is a bug introduced after I added the feature to speed up the dialog by pressing space. So I'll need to add some conditional logic if the input is focused, don't listen for space to speed up.

**Comment by maxcell** [comment]
I think that's an excellent way of make it conditional <3 I'll keep my eyes posted :D

**Comment by BolajiAyodeji** [comment]
Was about opening this.
I coudn't enter space hence I failed my command line quiz :cry:

**Comment by jsjoeio** [comment]
I think this will be fixed once the deployment updates but I'll test tomorrow before closing

**Comment by jsjoeio** [comment]
@andregce also pointed this out

**Comment by jsjoeio** [comment]
And @angiejones

**Comment by jsjoeio** [comment]
And @hazetheai

**Comment by jsjoeio** [comment]
And @hazetheai

**Comment by jsjoeio** [comment]
Yay! It's fixed in production now 😄

![spaces](https://user-images.githubusercontent.com/3806031/60397870-85e50a80-9b06-11e9-8fc2-78ef63007978.gif)

**Comment by maxcell** [comment]
Awesome work Joe! Thank you for creating an incredible experience!

**Comment by jsjoeio** [comment]
Let's hope this works correctly. 

@all-contributors please add @maxcell for bug

**Comment by jsjoeio** [comment]
@all-contributors please add @BolajiAyodeji for bug

**Comment by jsjoeio** [comment]
@all-contributors please add @andregce for bug

**Comment by jsjoeio** [comment]
@all-contributor please add @angiejones for bug

**Comment by jsjoeio** [comment]
@all-contributors please add @angiejones for bug

**Comment by jsjoeio** [comment]
@all-contributors please add @Hazetheai for bug

**Comment by jsjoeio** [comment]
So this has been fixed and all of you have been added to the contributors table in the README. Thank you! 😄

**Comment by BolajiAyodeji** [comment]
Thank you @jsjoeio for creating something awesome like this :tada:
