### ISSUE TITLE
Name input field suggested card payment autocomplete

### ISSUE THREAD

**Issue by benna100** [jsjoeio/mentored.dev#134]
When the professor asks for name it autocompletes card payment. 

Seems really shady. Checked the autocomplete, which looks fine. Immediately thought of this attack: https://empresas.blogthinkbig.com/how-to-take-advantage-of-chrome/

Anyway i closed the site because of this. Awesome idea though!

**Comment by jsjoeio** [comment]
Woah woah woah. That should not be happening. I am not using any autocomplete features at all. It's a simple text input field and this is the first I'm hearing of this.

@benna100 could you please provide steps to reproduce or a screenshot? This needs to be fixed.

I'm really sorry that happened by the way. And thank you for pointing it out.

**Comment by benna100** [comment]
Just add a letter in the name. On chrome newest version, windows 10.

![mspaint_o0DuB6nTLI](https://user-images.githubusercontent.com/4102007/60436374-2bce6d00-9c0c-11e9-9754-31b2ebd2eb4b.png)

**Comment by jsjoeio** [comment]
That's really bad... Okay. I'm going to see if I can reproduce it and I'll keep this open until it's fixed.

**Comment by jsjoeio** [comment]
Okay so I was able to reproduce it:

<img width="558" alt="image" src="https://user-images.githubusercontent.com/3806031/60448423-661f1680-9bda-11e9-881a-48b390d285d8.png">

I'll see if I can fix it with this: https://stackoverflow.com/a/16130452

**Comment by jsjoeio** [comment]
@benna100 I added a fix that seems to be working for me in Chrome.

Would you mind testing it to see if it's working on your side as well? https://staging.mentored.dev/

**Comment by benna100** [comment]
I think its really nice with the autocomplete for the name. It just sucks that it shows credit cards.

**Comment by benna100** [comment]
But it works fine, nothing shows up

**Comment by jsjoeio** [comment]
Yeah, it's just weird that it would show your credit card. Thanks for testing! 

@all-contributors please add @benna100 for bug and userTesting
